### ISSUE TITLE
Cannot read field "shaderFlags" because "material" is null

### ISSUE THREAD

**Issue by NatoBoram** [grondag/canvas#117]
Can reproduce while having only `fabric-api-0.24.1+build.412-1.16.jar` and `canvas-mc116-1.0.1033.jar` in the mods folder.
```yaml
# ---- Minecraft Crash Report ----
# Surprise! Haha. Well, this is awkward.

Time: 2020-10-24 16 h 22
Description: Rendering Particle

java.lang.NullPointerException: |
  Cannot read field "shaderFlags" because "material" is null 
  at grondag.canvas.wip.encoding.WipAbstractVertexCollector.vertexState(WipAbstractVertexCollector.java:92)
  at grondag.canvas.render.CanvasParticleRenderer.renderParticles(CanvasParticleRenderer.java:101)
  at grondag.canvas.render.CanvasWorldRenderer.renderWorld(CanvasWorldRenderer.java:794)
  at grondag.canvas.render.CanvasWorldRenderer.method_22710(CanvasWorldRenderer.java:1191)
  at net.minecraft.class_757.method_3188(class_757.java:727)
  at net.minecraft.class_757.method_3192(class_757.java:546)
  at net.minecraft.class_310.method_1523(class_310.java:1023)
  at net.minecraft.class_310.method_1514(class_310.java:656)
  at net.minecraft.client.main.Main.main(Main.java:215)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
  at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
  at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


# A detailed walkthrough of the error, its code path and all known details is as follows:
# ---------------------------------------------------------------------------------------

# -- Head --
Thread: Render thread
Stacktrace: |
  at grondag.canvas.wip.encoding.WipAbstractVertexCollector.vertexState(WipAbstractVertexCollector.java:92)

# -- Particle being rendered --
Details:
  Particle: class_717, Pos (79.48800505138016,73.01598648792185,-234.78823029876776), RGBA (0.27019018,0.27019018,0.27019018,1.0), Age 7
  Particle Type: PARTICLE_SHEET_OPAQUE
Stacktrace:
  at grondag.canvas.render.CanvasParticleRenderer.renderParticles(CanvasParticleRenderer.java:101)
  at grondag.canvas.render.CanvasWorldRenderer.renderWorld(CanvasWorldRenderer.java:794)
  at grondag.canvas.render.CanvasWorldRenderer.method_22710(CanvasWorldRenderer.java:1191)
  at net.minecraft.class_757.method_3188(class_757.java:727)

# -- Affected level --
Details:
  All players: 1 total; [class_746['NatoBoram'/527, l='ClientLevel', x=75.78, y=70.06, z=-246.41]]
  Chunk stats: Client Chunk Cache: 961, 464
  Level dimension: minecraft:overworld
  Level spawn location: World: (96,71,-239), Chunk: (at 0,4,1 in 6,-15; contains blocks 96,0,-240 to 111,255,-225), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Level time: 84896 game time, 8040107 day time
  Server brand: Paper
  Server type: Non-integrated multiplayer server
Stacktrace:
  at net.minecraft.class_638.method_8538(class_638.java:449)
  at net.minecraft.class_310.method_1587(class_310.java:2183)
  at net.minecraft.class_310.method_1514(class_310.java:674)
  at net.minecraft.client.main.Main.main(Main.java:215)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
  at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
  at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

# -- System Details --
Details:
  Minecraft Version: 1.16.3
  Minecraft Version ID: 1.16.3
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 15.0.1, Oracle Corporation
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
  Memory: 3058912536 bytes (2917 MB) / 4294967296 bytes (4096 MB) up to 8589934592 bytes (8192 MB)
  CPUs: 4
  JVM Flags: 22 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xms4G -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
  Fabric Mods: 
    autofish: Autofish 0.9.0
    blue_endless_jankson: jankson 1.1.2
    canvas: Canvas Renderer 1.0.1033
    cloth-basic-math: Cloth Basic Math 0.5.1
    cloth-config2: Cloth Config v4 4.8.2
    fabric: Fabric API 0.24.1+build.412-1.16
    fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
    fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
    fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
    fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
    fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
    fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
    fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
    fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
    fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
    fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
    fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.2+f8ac1db295
    fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
    fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
    fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
    fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
    fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
    fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
    fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
    fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
    fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
    fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
    fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.0+c270b09895
    fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
    fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
    fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.0+9f0fb4b895
    fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.2+2b46237995
    fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.2+2b46237995
    fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
    fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
    fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
    fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
    fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
    fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
    fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
    fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
    fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
    fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb895
    fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
    fabricloader: Fabric Loader 0.10.3+build.211
    fermion: Fermion 2.6.209
    fermion-orientation: Fermion Orientation 1.1.205
    fermion-varia: Fermion Varia 2.4.209
    frex: FREX 4.0.151
    inventoryprofiles: Inventory Profiles 0.4.2
    jankson: Jankson 3.0.1+j1.2.0
    json-model-extensions: JSON Model Extensions 1.16.133
    litematica: Litematica 0.0.0-dev.20200913.215807
    lithium: Lithium 0.5.6
    malilib: MaLiLib 0.10.0-dev.21+arne.1
    minecraft: Minecraft 1.16.3
    phosphor: Phosphor 0.6.0+build.7
    special-circumstances: Special Circumstances 1.7.209
    voxelmap: VoxelMap 1.10.11
  Launched Version: fabric-loader-0.10.3+build.211-1.16.3
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce GTX 660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fast
  Resource Packs: vanilla, fabric/fabric-renderer-api-v1, fabric/fabric-keybindings-v0, fabric/inventoryprofiles, fabric/fabricloader, fabric/fabric-containers-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-game-rule-api-v1, fabric/fabric-api-base, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-textures-v0, fabric/fabric-rendering-fluids-v1, fabric/fabric-blockrenderlayer-v1, fabric/fabric-lifecycle-events-v1, fabric/fabric-renderer-registries-v1, fabric/fabric-loot-tables-v1, fabric/fabric, fabric/fabric-networking-v0, fabric/fabric-screen-handler-api-v1, fabric/fabric-networking-blockentity-v0, fabric/fabric-tool-attribute-api-v1, fabric/fabric-renderer-indigo, fabric/autofish, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/fabric-item-api-v1, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-key-binding-api-v1, fabric/cloth-config2, fabric/fabric-resource-loader-v0, fabric/fabric-content-registries-v0, fabric/fabric-tag-extensions-v0, fabric/fabric-biome-api-v1, fabric/fabric-registry-sync-v0, fabric/fabric-mining-levels-v0, fabric/fabric-events-lifecycle-v0, fabric/fabric-item-groups-v0, fabric/fabric-models-v0, fabric/fabric-object-builders-v0, fabric/litematica (incompatible), fabric/malilib (incompatible), fabric/voxelmap (incompatible), file/Faithful-1.16.3.zip
  Current Language: English (Canada)
  CPU: 4x Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
```

**Comment by NatoBoram** [comment]
I updated to `1.0.1172-unstable` and the crash is gone
