### ISSUE TITLE
[1.0.1095] Incompatibility with Slight GUI Modifications

### ISSUE THREAD

**Issue by T0paz** [grondag/canvas#126]
I'm updating my mod list to 1.16.4 from 1.16.3, and noticed that, unlike in 1.16.3, Slight GUI Modifications 1.5.1 and Canvas 1.0.1095 are incompatible. Based on the logs, this is a conflict between the mixin "renderItemChangeY" in Slight GUI Mods and the mixin "MixinItemRenderer" in Canvas which both inject with priority 1000. 

> [main/FATAL]: Mixin apply failed slight-gui-modifications.mixins.json:MixinItemRenderer -> net.minecraft.class_918: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_918::renderItemChangeY with priority 1000 cannot inject into net/minecraft/class_918::method_23179(Lnet/minecraft/class_1799;Lnet/minecraft/class_809$class_811;ZLnet/minecraft/class_4587;Lnet/minecraft/class_4597;IILnet/minecraft/class_1087;)V merged by grondag.canvas.mixin.MixinItemRenderer with priority 1000 [PREINJECT Applicator Phase -> slight-gui-modifications.mixins.json:MixinItemRenderer -> Prepare Injections ->  -> handler$zdm000$renderItemChangeY(Lnet/minecraft/class_1799;Lnet/minecraft/class_809$class_811;ZLnet/minecraft/class_4587;Lnet/minecraft/class_4597;IILnet/minecraft/class_1087;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_918::renderItemChangeY with priority 1000 cannot inject into net/minecraft/class_918::method_23179(Lnet/minecraft/class_1799;Lnet/minecraft/class_809$class_811;ZLnet/minecraft/class_4587;Lnet/minecraft/class_4597;IILnet/minecraft/class_1087;)V merged by grondag.canvas.mixin.MixinItemRenderer with priority 1000 [PREINJECT Applicator Phase -> slight-gui-modifications.mixins.json:MixinItemRenderer -> Prepare Injections ->  -> handler$zdm000$renderItemChangeY(Lnet/minecraft/class_1799;Lnet/minecraft/class_809$class_811;ZLnet/minecraft/class_4587;Lnet/minecraft/class_4597;IILnet/minecraft/class_1087;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.10.6+build.214.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-loader-0.10.6+build.214.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_272]
	at net.minecraft.class_1921.<clinit>(class_1921.java:381) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.material.BlendMode.<clinit>(BlendMode.java:33) ~[47d1d52c-4d50-422a-8d0b-a37e54a6095e.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
	at java.lang.Class.getEnumConstantsShared(Class.java:3320) ~[?:1.8.0_272]
	at java.lang.Class.getEnumConstants(Class.java:3297) ~[?:1.8.0_272]
	at grondag.fermion.bits.BitPacker64$NullableEnumElement.<init>(BitPacker64.java:165) ~[97aaed99-521a-4f06-8f11-d434228785a6.jar:?]
	at grondag.fermion.bits.BitPacker64$NullableEnumElement.<init>(BitPacker64.java:159) ~[97aaed99-521a-4f06-8f11-d434228785a6.jar:?]
	at grondag.fermion.bits.BitPacker64.createNullableEnumElement(BitPacker64.java:66) ~[97aaed99-521a-4f06-8f11-d434228785a6.jar:?]
	at grondag.canvas.material.state.AbstractRenderStateView.<clinit>(AbstractRenderStateView.java:210) ~[canvas-mc116-1.0.1095-snapshot.jar:?]
	at grondag.canvas.apiimpl.Canvas.materialFinder(Canvas.java:73) ~[canvas-mc116-1.0.1095-snapshot.jar:?]
	at grondag.canvas.apiimpl.Canvas.<clinit>(Canvas.java:54) ~[canvas-mc116-1.0.1095-snapshot.jar:?]
	at grondag.canvas.CanvasMod.onInitializeClient(CanvasMod.java:66) ~[canvas-mc116-1.0.1095-snapshot.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33) [fabric-loader-0.10.6+build.214.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:437) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [intermediary-minecraft-1.16.4-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.6+build.214.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by Dolphin2Point1** [comment]
Fixed with shedaniel/slight-gui-modifications#11

**Comment by Dolphin2Point1** [comment]
[Shipped in 'Slight' Gui Modifications 1.6.1](https://www.curseforge.com/minecraft/mc-mods/slight-gui-modifications/files/3128212)

**Comment by spiralhalo** [comment]
I can confirm that the fix is working as expected. No other features of Slight GUI Modifications are affected besides the item rendering.

**Comment by grondag** [comment]
Looks like this is addressed.  Thanks!
