### ISSUE TITLE
Incompatibility With Java 11

### ISSUE THREAD

**Issue by InsomniaKitten** [grondag/canvas#14]
**Canvas version:** 0.6.42
**Fermion version:** 0.4.2
**Fabric version:** 0.3.0-pre+build.165

This is printed to the console when loading with Java 11.0.3

```
warn.canvas.slow_gl_call java.lang.NoSuchMethodException: java.nio.Bits.copyFromArray(java.lang.Object, long, long, long, long)
 at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
 at grondag.canvas.varia.CanvasGlHelper.initFastNioCopy(CanvasGlHelper.java:142)
 at grondag.canvas.varia.CanvasGlHelper.init(CanvasGlHelper.java:51)
 at net.minecraft.class_310.handler$hookInit$zbh000(class_310.java:3006)
 at net.minecraft.class_310.method_1503(class_310.java:613)
 at net.minecraft.class_310.method_1514(class_310.java:395)
 at net.minecraft.client.main.Main.main(Main.java:154)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
 at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
 at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
```

**Comment by grondag** [comment]
Was supposed to read: "Canvas unable to obtain a fast call path to %s due to reflection error. Render performance may be reduced." but it looks like localization failed somehow and there's really no need for it to dump the whole exception to log.

Fortunately, that code isn't even used now with JOML available so I removed the whole mess.
