### ISSUE TITLE
Incompatible with latest fabric

### ISSUE THREAD

**Issue by Mewtwoy** [grondag/canvas#168]
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fermion-modkeys'!
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
    at net.minecraft.client.MinecraftClient.redirect$zze000$stopFabricInit(MinecraftClient:3360)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:437)
    at net.minecraft.client.main.Main.main(Main:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/networking/v1/PacketSender
    at grondag.fermion.modkeys.ModKeysInit.onInitialize(ModKeysInit.java:26)
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher$LoaderClientReplacement$$Lambda$2374/951810282.accept(Unknown Source)
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher$LoaderClientReplacement$$Lambda$2375/124642485.accept(Unknown Source)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    ... 11 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.networking.v1.PacketSender
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 15 more
    
    WHY IS IT INCLUDING FERMION, I THOUGHT THIS WAS CANVAS

**Comment by Kichura** [comment]
Confirmed on this unit, Seems that fermion-modkeys is missing in their code; Thous without it, Canvas can't start.

**Comment by grondag** [comment]
Please update to latest Fabric API and latest Fabric Loader.

Canvas embeds Fermion, though it doesn't actually need ModKeys.  I'll have a look at that.

**Comment by Mewtwoy** [comment]
THE GAME NOW AUTOMATICALLY CRASHES ON MAIN MENU

Description: Unexpected error

java.lang.IllegalStateException: Cannot send packet to server while not in game!
    at net.fabricmc.fabric.impl.networking.ClientSidePacketRegistryImpl.sendToServer(ClientSidePacketRegistryImpl.java:51)
    at net.fabricmc.fabric.api.network.ClientSidePacketRegistry.sendToServer(ClientSidePacketRegistry.java:70)
    at net.fabricmc.fabric.api.network.ClientSidePacketRegistry.sendToServer(ClientSidePacketRegistry.java:89)
    at grondag.fermion.modkeys.impl.ModKeysHandler.sendUpdatePacket(ModKeysHandler.java:91)
    at grondag.fermion.modkeys.impl.ModKeysHandler.update(ModKeysHandler.java:83)
    at grondag.fermion.modkeys.ModKeysClientInit$$Lambda$5010/122171322.tick(Unknown Source)
    at net.fabricmc.fabric.impl.event.lifecycle.client.LegacyClientEventInvokers.lambda$onInitializeClient$0(LegacyClientEventInvokers.java:29)
    at net.fabricmc.fabric.impl.event.lifecycle.client.LegacyClientEventInvokers$$Lambda$5454/903184455.onEndTick(Unknown Source)
    at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
    at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents$$Lambda$2576/1109273519.onEndTick(Unknown Source)
    at net.minecraft.client.MinecraftClient.handler$cem000$onEndTick(MinecraftClient:10386)
    at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1612)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1021)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
    at net.minecraft.client.MinecraftClient.handler$bod000$afterCrashHandled(MinecraftClient:7404)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:704)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

**Comment by Kichura** [comment]
Have you tried running canvas without any other mod to see if the issue goes away?

**Comment by grondag** [comment]
I'll need an entire log to make much sense of this.

**Comment by Daiwenqian** [comment]
Hello, I have been dealing with a similar issue of the game constantly reloading once it reaches the main menu. I have provided my start up log below. 

[Start up log.txt](https://github.com/grondag/canvas/files/5745083/Start.up.log.txt)


I hope this helps, thanks for the help!

**Comment by grondag** [comment]
All of this should be fixed in latest versions.  Please reopen if otherwise.
