### ISSUE TITLE
ArrayIndexOutOfBoundsException crash during dimension loading caused by Block Entity rendering

### ISSUE THREAD

**Issue by spiralhalo** [grondag/canvas#192]
Crash happens only *during* dimension loading and only when block entity is *on sight*. From my test, if I look away from any block entity until the dimension initial chunks loading is completed, it won't crash.

Also note that it's not easy to reproduce this crash, but one way to try is to make a world filled with item frame and banner. Once the crash happens in will repeat consistently upon subsequent dimension/world loading *unless* the player looks away from the block entities.

Seems similar to #157 at first but upon looking at the stack trace seem completely different. (?)

My crash reports are from the configurable pipeline branch but I've experienced this crash several times before with the CurseForge release. I will put up more crash reports if I got another crash with the CurseForge release.

### Crash reports:
https://gist.github.com/spiralhalo/b0a23d18b735a550e2bd2d1482c0e269

### Key details:
```
Description: Rendering Block Entity
```
```
Thread: Render thread
```
```
-- Entity being rendered --
Details:
	Entity Type: minecraft:item_frame (net.minecraft.class_1533)
```
crash report 1:
```
java.lang.ArrayIndexOutOfBoundsException: 8192
	at grondag.canvas.buffer.encoding.AbstractVertexCollector.method_23919(AbstractVertexCollector.java:167)
```
crash report 2:
```
java.lang.ArrayIndexOutOfBoundsException: 4096
	at grondag.canvas.buffer.encoding.AbstractVertexCollector.method_23919(AbstractVertexCollector.java:167)
```

**Comment by spiralhalo** [comment]
From a quick look at the code the affected class doesn't exist anymore.
