### ISSUE TITLE
client in an start loop

### ISSUE THREAD

**Issue by MSandro** [grondag/canvas#194]
Hi, I can't start my modpack with Canvas. It seems to be in an Start-Loop. The loading-progress bar is showing many times ...
Because the Client is not crashing I can only provide an errror part of my latest.log:
```
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: grondag.canvas.apiimpl.mesh.MutableQuadViewImpl.spriteFloat(IIFF)Lgrondag/canvas/apiimpl/mesh/MutableQuadViewImpl;
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:659) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014$$Lambda$10563/1868423194.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014$$Lambda$10035/582756300.execute(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014$$Lambda$10563/1868423194.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014$$Lambda$10035/582756300.execute(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014$$Lambda$10563/1868423194.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014$$Lambda$10035/582756300.execute(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014$$Lambda$10563/1868423194.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014$$Lambda$10035/582756300.execute(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014$$Lambda$10563/1868423194.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014$$Lambda$10035/582756300.execute(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014$$Lambda$10563/1868423194.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4014$$Lambda$10035/582756300.execute(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.class_1060$$Lambda$10574/1282378484.execute(Unknown Source) ~[?:?]
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:116) ~[intermediary-1.16.4.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:103) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:308) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1068) [intermediary-1.16.4.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-1.16.4.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-1.16.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171) [jumploader-2.1.2.jar:2.1.2]
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/692331943.accept(Unknown Source) [modlauncher-8.0.6.jar:?]
	at java.util.HashMap$Values.forEach(HashMap.java:972) [?:1.8.0_51]
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
Caused by: java.lang.NoSuchMethodError: grondag.canvas.apiimpl.mesh.MutableQuadViewImpl.spriteFloat(IIFF)Lgrondag/canvas/apiimpl/mesh/MutableQuadViewImpl;
	at net.dblsaiko.hctm.client.render.model.CanvasRenderPlatform.spriteFix(CanvasRenderPlatform.java:32) ~[40ca0b90-c619-47e6-93e4-08d84d440ba8.jar:?]
	at net.dblsaiko.hctm.client.render.model.RenderPlatformKt.spriteFix(RenderPlatformKt.java:17) ~[40ca0b90-c619-47e6-93e4-08d84d440ba8.jar:?]
	at net.dblsaiko.hctm.client.render.model.Quad.into(Quad.java:371) ~[40ca0b90-c619-47e6-93e4-08d84d440ba8.jar:?]
	at net.dblsaiko.hctm.client.render.model.UnbakedWireModelKt.into(UnbakedWireModelKt.java:457) ~[40ca0b90-c619-47e6-93e4-08d84d440ba8.jar:?]
	at net.dblsaiko.hctm.client.render.model.UnbakedWireModelKt.access$into(UnbakedWireModelKt.java:1) ~[40ca0b90-c619-47e6-93e4-08d84d440ba8.jar:?]
	at net.dblsaiko.hctm.client.render.model.UnbakedWireModel.generateCenter(UnbakedWireModel.java:160) ~[40ca0b90-c619-47e6-93e4-08d84d440ba8.jar:?]
	at net.dblsaiko.hctm.client.render.model.UnbakedWireModel.generateSide(UnbakedWireModel.java:124) ~[40ca0b90-c619-47e6-93e4-08d84d440ba8.jar:?]
	at net.dblsaiko.hctm.client.render.model.UnbakedWireModel.generateParts(UnbakedWireModel.java:120) ~[40ca0b90-c619-47e6-93e4-08d84d440ba8.jar:?]
	at net.dblsaiko.hctm.client.render.model.UnbakedWireModel.access$generateParts(UnbakedWireModel.java:49) ~[40ca0b90-c619-47e6-93e4-08d84d440ba8.jar:?]
	at net.dblsaiko.hctm.client.render.model.UnbakedWireModel$bake$parts$1.apply(UnbakedWireModel.java:113) ~[40ca0b90-c619-47e6-93e4-08d84d440ba8.jar:?]
	at net.dblsaiko.hctm.client.render.model.UnbakedWireModel$bake$parts$1.apply(UnbakedWireModel.java:49) ~[40ca0b90-c619-47e6-93e4-08d84d440ba8.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_51]
	at net.dblsaiko.hctm.client.render.model.UnbakedWireModel.method_4753(UnbakedWireModel.java:107) ~[40ca0b90-c619-47e6-93e4-08d84d440ba8.jar:?]
	at net.minecraft.class_1088.method_15878(class_1088.java:486) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_1088.method_4733(class_1088.java:249) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_1088$$Lambda$10596/1676570613.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:928) ~[?:1.8.0_51]
	at net.minecraft.class_1088.method_18177(class_1088.java:246) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_1092.method_18179(class_1092.java:67) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_1092.method_18788(class_1092.java:19) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.class_4080$$Lambda$10048/907768625.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_51]
	... 101 more
```

**Comment by Daiwenqian** [comment]
I have been dealing with the same issue going back to canvas release 1000+, here is a full boot log for easier understanding of what is happening. 
[boot loop.txt](https://github.com/grondag/canvas/files/5826623/boot.loop.txt)

**Comment by IMS212** [comment]
seems to be related to 2xsaiko/hctm-base#2

**Comment by dblsaiko** [comment]
Yeah that's not a canvas issue, that's an issue with RSWires/hctm-base. It's been compiled against canvas 1.0.996, so try with that. I missed that there are versions above that so I'll release a new version with newer canvas support if I can find an equivalent, at least until #193 is fixed.

**Comment by dblsaiko** [comment]
Could you try [rswires 4.10.1][1]? It's compiled against canvas 1.0.1267 now, and should work.

[1]: https://ci.dblsaiko.net/job/rswires/14/

**Comment by irunatbullets** [comment]
Confirmed. No start loop with rswires 4.10.1.

**Comment by mcdodge34** [comment]
Will wait for pack update of all of fabirc 3 and see if they will update rswires in their updates and then retry canvas and see what happens then.

**Comment by irunatbullets** [comment]
They will, I've just updated the faq in aof3 with advice for getting canvas running.

**Comment by spiralhalo** [comment]
From what I gather, this is an incompatibility with RSWires? Can't reproduce with Canvas 1.0.1511 and RSWires 4.10.2. I assume this is resolved.
