### ISSUE TITLE
Crash when opening 1.0.1267

### ISSUE THREAD

**Issue by NatoBoram** [grondag/canvas#208]
Hi! I am currently unable to open the release `1.0.1267` and eafac824fd9f6489b272d948669377433c6e6467 built from source. Here's the crash logs.

```yaml
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2021-02-10 19 h 28
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'canvas'!
  at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
  at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
  at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
  at net.minecraft.class_310.<init>(class_310.java:437)
  at net.minecraft.client.main.Main.main(Main.java:177)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
  at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
  at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
  Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/rendering/v1/WorldRenderEvents
    at grondag.frex.api.event.FrexEventInit.onInitializeClient(FrexEventInit.java:28)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    ... 11 more
  Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.rendering.v1.WorldRenderEvents
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    ... 13 more
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/rendering/v1/WorldRenderEvents
  at grondag.canvas.compat.Compat.init(Compat.java:33)
  at grondag.canvas.CanvasMod.onInitializeClient(CanvasMod.java:85)
  at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
  ... 11 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.rendering.v1.WorldRenderEvents
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
  at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
  ... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
  at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
  at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
  at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
  at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
  at net.minecraft.client.main.Main.main(Main.java:177)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
  at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
  at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 15.0.2, Oracle Corporation
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
  Memory: 1096154696 bytes (1045 MB) / 1409286144 bytes (1344 MB) up to 8589934592 bytes (8192 MB)
  CPUs: 4
  JVM Flags: 21 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
  Fabric Mods: 
    blue_endless_jankson: jankson 1.1.2
    canvas: Canvas Renderer 1.0.1267
    cloth-basic-math: Cloth Basic Math 0.5.1
    cloth-config2: Cloth Config v4 4.8.3
    fabric: Fabric API 0.28.4+1.16
    fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
    fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
    fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
    fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
    fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
    fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
    fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
    fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
    fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
    fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
    fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
    fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
    fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
    fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
    fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
    fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
    fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
    fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
    fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
    fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
    fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
    fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
    fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
    fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
    fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
    fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
    fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
    fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
    fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
    fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
    fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
    fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
    fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
    fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
    fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.0+552549d53a
    fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
    fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
    fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
    fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
    fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
    fabricloader: Fabric Loader 0.10.7
    fermion: Fermion 2.9.218
    fermion-orientation: Fermion Orientation 1.2.218
    fermion-varia: Fermion Varia 2.6.218
    frex: FREX 4.5.201
    frex-events: FREX Events 1.3.13
    jankson: Jankson 3.0.1+j1.2.0
    json-model-extensions: JSON Model Extensions 1.19.172
    minecraft: Minecraft 1.16.4
    special-circumstances: Special Circumstances 1.8.218
  Launched Version: fabric-loader-0.10.7-1.16.4
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: NO CONTEXT
  GL Caps: 
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  CPU: <unknown>
```

**Comment by supsm** [comment]
You need at least fabric api 0.29 for this version of canvas, if I recall correctly.

**Comment by NatoBoram** [comment]
Oh right. It works now.

I don't notice the bloom on torches anymore, is there something changed about it?

**Comment by Reeses-Puffs** [comment]
no, I think you just need to enable canvas/default in the resource packs menu to make bloom work

**Comment by NatoBoram** [comment]
Oh thanks! That's what I was missing
