### ISSUE TITLE
Invisable everythink under certain complex but common conditions.

### ISSUE THREAD

**Issue by sharpenedblade** [grondag/canvas#253]
Blocks turn invisible in canvas basic, dev, and, lumilights. to reproduce:
1. fly above y=650
2. travel outside render distance
3. fly down
4. observe no blocks but you cant go down more.

**Comment by spiralhalo** [comment]
I found an easier way to reproduce (possibly) this bug:
1. `/tp ~ 1000 ~` (todo: narrow down minimum y)
2. `/tp ~ 100 ~`
3. observe that loaded chunks might still render, but no new chunks (regions) will load.
4. switch to third person view, walk into unrendered chunk, observe player entity disappearing.
5. press f3+a, observe that nothing is rendered anymore, except the sky.
6. reload world, nothing is rendered. (restart is the only solution)

Reproducible in mc117-1.17-1.0.1639-unstable (latest as of writing)

Exception:
```log
[00:03:48] [Canvas Render Thread - 6/ERROR]: Unhandled error during rendering. Impact unknown.
java.lang.ArrayIndexOutOfBoundsException: Index 2147483647 out of bounds for length 328509
	at grondag.canvas.terrain.occlusion.CameraPotentiallyVisibleRegionSet.add(CameraPotentiallyVisibleRegionSet.java:140) ~[canvas-mc117-1.17-1.0.1639.jar:?]
	at grondag.canvas.terrain.region.BuiltRenderRegion.addToCameraPvsIfValid(BuiltRenderRegion.java:855) ~[canvas-mc117-1.17-1.0.1639.jar:?]
	at grondag.canvas.terrain.occlusion.TerrainIterator.run(TerrainIterator.java:140) ~[canvas-mc117-1.17-1.0.1639.jar:?]
	at grondag.canvas.terrain.util.TerrainExecutor$Worker.run(TerrainExecutor.java:110) [canvas-mc117-1.17-1.0.1639.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

Full log: https://gist.github.com/spiralhalo/bae3c7af26e3ac69b267a2a286cba7d1

**Comment by spiralhalo** [comment]
Just in case: still reproducible with only Canvas and ~~modmenu~~ fabric api (edit: wtf).
