### ISSUE TITLE
[BUG] Does not work with Litematica

### ISSUE THREAD

**Issue by polarbub** [grondag/canvas#271]
Affected Canvas versions: 1.17-1.0.1582

Description of the issue:
Does not work with Litematica
Without Canvas: 
![image](https://cdn.discordapp.com/attachments/816392091009024010/851917317213519932/2021-06-08_15.15.00.png)
With Canvas:
![image](https://cdn.discordapp.com/attachments/816392091009024010/851918025266298900/2021-06-08_15.17.45.png)

Link to paste site with logs:
https://pastebin.com/tCpzqQuS
https://pastebin.com/Nm9802k3

**Comment by spiralhalo** [comment]
MiniHUD doesn't work either. Since they have similar hooks/holder, I'll just add it here

```log
[03:03:34] [Render thread/WARN]: Unable to find MaliLib render hook due to exception:
java.lang.NoSuchMethodException: fi.dy.masa.malilib.event.RenderEventHandler.onRenderWorldLast(net.minecraft.class_4587,net.minecraft.class_310,float)
	at java.lang.Class.getDeclaredMethod(Class.java:2613) ~[?:?]
	at grondag.canvas.compat.MaliLibHolder.<clinit>(MaliLibHolder.java:43) ~[canvas-mc117-1.17-1.0.1655.jar:?]
	at grondag.canvas.compat.Compat.lambda$init$5(Compat.java:68) ~[canvas-mc117-1.17-1.0.1655.jar:?]
	at grondag.canvas.render.CanvasWorldRenderer.renderWorld(CanvasWorldRenderer.java:715) [canvas-mc117-1.17-1.0.1655.jar:?]
	at grondag.canvas.render.CanvasWorldRenderer.method_22710(CanvasWorldRenderer.java:851) [canvas-mc117-1.17-1.0.1655.jar:?]
...
```

Potentially easy fix for the holders, unless it requires third party intervention.

**Comment by Polarbub** [comment]
I think this is more a problem w/ Malilib than any of the mods that use it. I would think it also breaks some visual things from Tweakeroo too.

**Comment by polarbub** [comment]
thanks :)

**Comment by spiralhalo** [comment]
you're welcome. let me know if it still has problems as I don't use litematica extensively.

**Comment by sharpenedblade** [comment]
The overlay has to little contrast compared to vanilla litematica
