### ISSUE TITLE
Voxel Map Incompatibility

### ISSUE THREAD

**Issue by LazyKB** [grondag/canvas#311]
**System Informatinon**

- Minecraft Version: 1.17
- Canvas Version: 1851 Unstable (latest)
- Operating System: Windows
- Graphics Card: Nvidia GTX 1060

**Other mods and versions installed**

- fabric-1.2.3
- Voxel Map

**How you triggered the behavior**

- start minecraft
- log into any world with mobs while radar is enabled on Voxel map
- look at a certain angle direction or location.

**What you expected would happen** 

- The radar icon would appear on the Minimap

**What actually happened**

- The radar icons appear on the bottom left of the screen for one frame and tank FPS when they render

This DOES NOT occur when Radar is turned off. The issue is that something between Voxel map and Canvas is making the game not sure where to put the radar icons. According to Awoo's knowledge and my memory this started when Canvas took the pipeline approach for users, as this didn't happen in the older 1.16 versions. (Before fancy fab, and fast graphics were replaced by pipeline options and canvas options was just a long list of settings.)

**Logs and screenshots**

This error is put in the log every time the issue occurs (it happens often)

[15:47:03] [Render thread/INFO]: [STDERR]: (x + width) is outside of Raster
[15:47:03] [Render thread/INFO]: [STDERR]: java.awt.image.RasterFormatException: (x + width) is outside of Raster
[15:47:03] [Render thread/INFO]: [STDERR]: 	at java.desktop/sun.awt.image.ByteInterleavedRaster.createWritableChild(ByteInterleavedRaster.java:1240)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at java.desktop/java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1202)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.util.ImageUtils.trim(ImageUtils.java:660)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.Radar.trimAndOutlineImage(Radar.java:1676)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.Radar.createAutoIconImageFromResourceLocations(Radar.java:1463)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.Radar.tryAutoIcon(Radar.java:1138)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.Radar.calculateMobs(Radar.java:841)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.Radar.onTickInGame(Radar.java:738)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.Map.drawMinimap(Map.java:1146)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.Map.onTickInGame(Map.java:755)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.VoxelMap.onTickInGame(VoxelMap.java:191)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.fabricmod.FabricModVoxelMap.renderOverlay(FabricModVoxelMap.java:74)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_329.handler$znd000$onRenderGameOverlay(class_329.java:3483)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_329.method_1753(class_329.java:406)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:855)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1112)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:728)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:217)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[15:47:03] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by LazyKB** [comment]
Latest build this issue still happens however FPS is not dropped now, log is still spammed though.
