### ISSUE TITLE
Crash when exiting

### ISSUE THREAD

**Issue by OS-Void** [grondag/canvas#320]
**System Informatinon**

- Minecraft Version: 1.17.1
- Canvas Version: mc117-1.17-1.0.1895
- Operating System: arch 5.13.7-arch1-1
- Graphics Card: 2080 Ti

**Other mods and versions installed**
  - InventorySorter-1.7.9-1.17
  - canvas-mc117-1.17-1.0.1895
  - clear-skies-mc117-1.5.70
  - ctm-fabric-0.5.0+1.17
  - custom-fog-1.6.0
  - fabric-api-0.37.1+1.17
  - fabric-carpet-1.17.1-1.4.43+v210706
  - fancymenu_fabric_2.2.0-2_MC_1.17-1.17.1
  - hydrogen-fabric-mc1.17.1-0.3
  - konkrete_fabric_1.2.3_MC_1.17-1.17.1
  - lazydfu-0.1.2
  - litematica-fabric-1.17.0-0.0.0-dev.20210616.033538
  - lithium-fabric-mc1.17.1-0.7.3
  - malilib-fabric-1.17.1-0.10.0-dev.24
  - minihud-fabric-1.17.1-0.19.0-dev.20210707.150016
  - modmenu-2.0.2
  - nobreak-1.1-1.17.1+
  - nofade-1.17-2.0.0
  - preciseblockplacing-1.07+1.17
  - smoothboot-fabric-1.16.5-1.6.0
  - starlight-1.0.0-RC3+fabric.1.17.x
  - voicechat-fabric-1.17.1-1.0.0

**How you triggered the behavior**

So far it has only happened when I'm exiting the game

**What you expected would happen**

The game to close normally

**What actually happened**

The game hangs for a very short amount of time and closes, but throws errors at the logs.

**Logs and screenshots**

```
[15:05:21] [Render thread/FATAL]: Unreported exception thrown!
java.lang.UnsupportedOperationException: Dedicated terrain executor recevied shared-mode task
	at grondag.canvas.terrain.util.DedicatedTerrainExecutor.execute(DedicatedTerrainExecutor.java:117) ~[canvas-mc117-1.17-1.0.1895.jar:?]
	at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1778) ~[?:?]
	at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2001) ~[?:?]
	at net.minecraft.class_4237.method_19746(class_4237.java:30) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
	at net.minecraft.class_4237.method_19743(class_4237.java:30) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1140.method_4854(class_1140.java:392) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1144.method_4873(class_1144.java:225) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_638.method_8486(class_638.java:406) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2258.method_9496(class_2258.java:120) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_638.method_2943(class_638.java:300) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_638.method_2941(class_638.java:275) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1791) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1081) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[15:05:21] [Render thread/INFO]: Disconnecting client
---- Minecraft Crash Report ----
// You're mean.

Time: 8/6/21, 3:05 PM
Description: Unexpected error

java.lang.UnsupportedOperationException: Dedicated terrain executor recevied shared-mode task
	at grondag.canvas.terrain.util.DedicatedTerrainExecutor.execute(DedicatedTerrainExecutor.java:117)
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1778)
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2001)
	at net.minecraft.class_4237.method_19746(class_4237.java:30)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.minecraft.class_4237.method_19743(class_4237.java:30)
	at net.minecraft.class_1140.method_4854(class_1140.java:392)
	at net.minecraft.class_1144.method_4873(class_1144.java:225)
	at net.minecraft.class_638.method_8486(class_638.java:406)
	at net.minecraft.class_2258.method_9496(class_2258.java:120)
	at net.minecraft.class_638.method_2943(class_638.java:300)
	at net.minecraft.class_638.method_2941(class_638.java:275)
	at net.minecraft.class_310.method_1574(class_310.java:1791)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at grondag.canvas.terrain.util.DedicatedTerrainExecutor.execute(DedicatedTerrainExecutor.java:117)
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1778)
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2001)
	at net.minecraft.class_4237.method_19746(class_4237.java:30)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.minecraft.class_4237.method_19743(class_4237.java:30)
	at net.minecraft.class_1140.method_4854(class_1140.java:392)
	at net.minecraft.class_1144.method_4873(class_1144.java:225)
	at net.minecraft.class_638.method_8486(class_638.java:406)
	at net.minecraft.class_2258.method_9496(class_2258.java:120)
	at net.minecraft.class_638.method_2943(class_638.java:300)
	at net.minecraft.class_638.method_2941(class_638.java:275)

-- Affected level --
Details:
	All players: 1 total; [class_746['iPollox'/213306, l='ClientLevel', x=2063.64, y=13.00, z=-276.26]]
	Chunk stats: 2601, 2178
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 93917810 game time, 96946304 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by spiralhalo** [comment]
should be fixed by 0518d3d3da086c691c902af5055d0d044a14bb1b
