### ISSUE TITLE
Placing a string block crashes the game

### ISSUE THREAD

**Issue by AlexGarrity** [grondag/canvas#44]
Placing a string block will crash the game.  No other block tested (which was most of them, including all non full-block models and blocks which may use the same renderer) will cause this issue.

I've attached the full log file, but the relevant part is below
[latest.log](https://github.com/grondag/canvas/files/4834163/latest.log)

```
[23:33:22] [main/FATAL]: Reported exception thrown!
net.minecraft.class_148: Tesselating block in world - Indigo Renderer
	at grondag.canvas.apiimpl.rendercontext.TerrainRenderContext.tesselateBlock(TerrainRenderContext.java:112) ~[canvas-mc116-1.0.716.jar:?]
	at grondag.canvas.chunk.BuiltRenderRegion.buildTerrain(BuiltRenderRegion.java:418) ~[canvas-mc116-1.0.716.jar:?]
	at grondag.canvas.chunk.BuiltRenderRegion.rebuildOnMainThread(BuiltRenderRegion.java:499) ~[canvas-mc116-1.0.716.jar:?]
	at grondag.canvas.render.CanvasWorldRenderer.buildNearRegion(CanvasWorldRenderer.java:302) ~[canvas-mc116-1.0.716.jar:?]
	at grondag.canvas.render.CanvasWorldRenderer.setupTerrain(CanvasWorldRenderer.java:222) ~[canvas-mc116-1.0.716.jar:?]
	at grondag.canvas.render.CanvasWorldRenderer.renderWorld(CanvasWorldRenderer.java:358) ~[canvas-mc116-1.0.716.jar:?]
	at net.minecraft.class_761.handler$zbd000$render(class_761.java:3264) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:717) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:540) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1021) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:654) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.8+build.202.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.8+build.202.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.8+build.202.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at grondag.canvas.apiimpl.RenderMaterialImpl$CompositeMaterial.forBlendMode(RenderMaterialImpl.java:253) ~[canvas-mc116-1.0.716.jar:?]
	at grondag.canvas.apiimpl.rendercontext.FallbackConsumer.renderQuad(FallbackConsumer.java:146) ~[canvas-mc116-1.0.716.jar:?]
	at grondag.canvas.apiimpl.rendercontext.FallbackConsumer.acceptInsideQuads(FallbackConsumer.java:120) ~[canvas-mc116-1.0.716.jar:?]
	at grondag.canvas.apiimpl.rendercontext.FallbackConsumer.accept(FallbackConsumer.java:94) ~[canvas-mc116-1.0.716.jar:?]
	at grondag.canvas.apiimpl.rendercontext.FallbackConsumer.accept(FallbackConsumer.java:55) ~[canvas-mc116-1.0.716.jar:?]
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1045) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at grondag.canvas.apiimpl.rendercontext.TerrainRenderContext.tesselateBlock(TerrainRenderContext.java:107) ~[canvas-mc116-1.0.716.jar:?]
	... 19 more
```

**Comment by grondag** [comment]
Whoa, it does!  Thank you for reporting it.  

Will get it fixed for the next build.
