### ISSUE TITLE
Canvas crash upon joining world... Ok Zoomer mod incompatibilty??? [java.lang.NoSuchMethodError: net.minecraft.class_638.method_29287()Lnet/minecraft/class_5321;]

### ISSUE THREAD

**Issue by technodono** [grondag/canvas#80]
Whenwver I open world with the newest version of fabric and all mods, the game crashes when joining a world... Have no idea if the other mod OKzoomer is affecting this or not.

System information:
Windnows 10
Running - Minecraft Java edition 1.6.2 on fabric with mods: Canvas, OkZoomer, ModMenu

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 16/08/20 10:17 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.class_638.method_29287()Lnet/minecraft/class_5321;
	at grondag.canvas.varia.WorldDataManager.update(WorldDataManager.java:69)
	at grondag.canvas.shader.MaterialShaderManager.prepareForFrame(MaterialShaderManager.java:154)
	at grondag.canvas.render.CanvasWorldRenderer.setupTerrain(CanvasWorldRenderer.java:198)
	at grondag.canvas.render.CanvasWorldRenderer.renderWorld(CanvasWorldRenderer.java:367)
	at grondag.canvas.render.CanvasWorldRenderer.method_22710(CanvasWorldRenderer.java:1047)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1023)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at grondag.canvas.varia.WorldDataManager.update(WorldDataManager.java:69)
	at grondag.canvas.shader.MaterialShaderManager.prepareForFrame(MaterialShaderManager.java:154)
	at grondag.canvas.render.CanvasWorldRenderer.setupTerrain(CanvasWorldRenderer.java:198)
	at grondag.canvas.render.CanvasWorldRenderer.renderWorld(CanvasWorldRenderer.java:367)
	at grondag.canvas.render.CanvasWorldRenderer.method_22710(CanvasWorldRenderer.java:1047)
	at net.minecraft.class_757.method_3188(class_757.java:727)

-- Affected level --
Details:
	All players: 1 total; [class_746['Technodono'/61, l='ClientLevel', x=51.84, y=238.00, z=193.22]]
	Chunk stats: Client Chunk Cache: 1369, 315
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,237,0), Chunk: (at 0,14,0 in 1,0; contains blocks 16,0,0 to 31,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 209460 game time, 165684 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_310.method_1514(class_310.java:679)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1136960992 bytes (1084 MB) / 1912602624 bytes (1824 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		blue_endless_jankson: jankson 1.1.2
		canvas: Canvas Renderer 1.0.871
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.7.0-unstable
		fabric: Fabric API 0.18.0+build.397-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c4e
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b4e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+fac8f3664e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.6.0+e81ec80b4e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+ba4afa574e
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a704e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.3+e5d3217f4e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+5d32f5834e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.10+e5d3217f4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.2.0+fc24ff244e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.9+e5d3217f4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.1+02fb8fda4e
		fabricloader: Fabric Loader 0.9.1+build.205
		fermion: Fermion 2.2.193
		fermion-orientation: Fermion Orientation 1.0.180-snapshot
		fermion-varia: Fermion Varia 2.1.193
		fiber: fiber 0.23.0-2
		frex: FREX 3.2.132
		jankson: Jankson 3.0.0+j1.2.0
		joml-mod: JOML Mod 1.4.20
		json-model-extensions: JSON Model Extensions 1.11.116
		minecraft: Minecraft 1.16.2
		modmenu: Mod Menu 1.14.6+build.31
		okzoomer: Ok Zoomer 4.0.0-beta.3+1.16.2
		special-circumstances: Special Circumstances 1.6.193
	Launched Version: fabric-loader-0.9.1+build.205-1.16.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: vanilla, file/Beta relics
	Current Language: English (Australia)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 
```

**Comment by grondag** [comment]
This is probably because I am a doofus and never uploaded the 1.16.2 compatible version to curse forge.  It's there now:  https://www.curseforge.com/minecraft/mc-mods/canvas-renderer/files/3039518
